### ISSUE TITLE
errors while running code on gradio

### ISSUE THREAD

**Issue by w1xmovies** [Kevin-thu/DiffMorpher#16]
Hello.
I've followed pretty simple installation rules and I get following errors while executing DiffMorpher. 
The first time I've cloned the repo I did not download pretrained models from hugginface and on the first run it did it by itself. When I hit Run it succesfully created LoRas, but on the execution it failed.
After that I've downloaded pretrained models repo and placed it inside DiffMorpher/stabilityai/stable-diffusion-2-1-base folder.

This is what I get on miniconda prompt
```
(mrp) F:\ComfyUI\DiffMorpher>python app.py
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\lpips\weights\v0.1\alex.pth
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "F:\ComfyUI\DiffMorpher\app.py", line 47, in run_diffmorpher
    morpher_pipeline = DiffMorpherPipeline.from_pretrained(model_path, torch_dtype=torch.float32).to("cuda")
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1101, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "F:\ComfyUI\DiffMorpher\model.py", line 108, in __init__
    super().__init__(vae, text_encoder, tokenizer, unet, scheduler,
TypeError: StableDiffusionPipeline.__init__() takes from 8 to 9 positional arguments but 10 were given
Traceback (most recent call last):
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "F:\ComfyUI\DiffMorpher\app.py", line 47, in run_diffmorpher
    morpher_pipeline = DiffMorpherPipeline.from_pretrained(model_path, torch_dtype=torch.float32).to("cuda")
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1101, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "F:\ComfyUI\DiffMorpher\model.py", line 108, in __init__
    super().__init__(vae, text_encoder, tokenizer, unet, scheduler,
TypeError: StableDiffusionPipeline.__init__() takes from 8 to 9 positional arguments but 10 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\w1xmo\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

**Comment by Kevin-thu** [comment]
Hi, sorry for the inconvenience caused to you. We have fixed it now. Please pull it from GitHub and try it again.

**Comment by w1xmovies** [comment]
Hey!
Update the repo and it further but still without success.

```
(mrp) F:\GitHubRepos\DiffMorpher>python app.py
Setting up [LPIPS] perceptual loss: trunk [alex], v[0.1], spatial [off]
C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

DDIM inversion: 100%|██████████████████████████████████████████████████████████████████| 51/51 [00:02<00:00, 23.15it/s]
DDIM inversion: 100%|██████████████████████████████████████████████████████████████████| 51/51 [00:02<00:00, 24.59it/s]
latents shape:  torch.Size([1, 4, 64, 64])
DDIM Sampler, alpha=0.0:   0%|                                                                  | 0/51 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "F:\GitHubRepos\DiffMorpher\app.py", line 107, in run_all
    return run_diffmorpher(
  File "F:\GitHubRepos\DiffMorpher\app.py", line 58, in run_diffmorpher
    images = morpher_pipeline(
  File "F:\GitHubRepos\DiffMorpher\model.py", line 614, in __call__
    images_pt = morph(alpha_list, progress, "Sampling...")
  File "F:\GitHubRepos\DiffMorpher\model.py", line 495, in morph
    latents = self.cal_latent(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\GitHubRepos\DiffMorpher\model.py", line 331, in cal_latent
    noise_pred = self.unet(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\unet_2d_condition.py", line 848, in forward
    sample = upsample_block(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 2017, in forward
    hidden_states = attn(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\transformer_2d.py", line 296, in forward
    hidden_states = block(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\attention.py", line 144, in forward
    attn_output = self.attn1(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\attention_processor.py", line 320, in forward
    return self.processor(
  File "F:\GitHubRepos\DiffMorpher\model.py", line 36, in __call__
    res = self.original_processor(attn, hidden_states, *args,
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\attention_processor.py", line 1295, in __call__
    query = attn.to_q(hidden_states) + scale * self.to_q_lora(hidden_states)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\attention_processor.py", line 528, in forward
    down_hidden_states = self.down(hidden_states.to(dtype))
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x1280 and 320x16)
Traceback (most recent call last):
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\queueing.py", line 456, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\blocks.py", line 1522, in process_api
    result = await self.call_function(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\blocks.py", line 1144, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\utils.py", line 674, in wrapper
    response = f(*args, **kwargs)
  File "F:\GitHubRepos\DiffMorpher\app.py", line 107, in run_all
    return run_diffmorpher(
  File "F:\GitHubRepos\DiffMorpher\app.py", line 58, in run_diffmorpher
    images = morpher_pipeline(
  File "F:\GitHubRepos\DiffMorpher\model.py", line 614, in __call__
    images_pt = morph(alpha_list, progress, "Sampling...")
  File "F:\GitHubRepos\DiffMorpher\model.py", line 495, in morph
    latents = self.cal_latent(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\GitHubRepos\DiffMorpher\model.py", line 331, in cal_latent
    noise_pred = self.unet(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\unet_2d_condition.py", line 848, in forward
    sample = upsample_block(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\unet_2d_blocks.py", line 2017, in forward
    hidden_states = attn(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\transformer_2d.py", line 296, in forward
    hidden_states = block(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\attention.py", line 144, in forward
    attn_output = self.attn1(
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\attention_processor.py", line 320, in forward
    return self.processor(
  File "F:\GitHubRepos\DiffMorpher\model.py", line 36, in __call__
    res = self.original_processor(attn, hidden_states, *args,
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\attention_processor.py", line 1295, in __call__
    query = attn.to_q(hidden_states) + scale * self.to_q_lora(hidden_states)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\diffusers\models\attention_processor.py", line 528, in forward
    down_hidden_states = self.down(hidden_states.to(dtype))
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x1280 and 320x16)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\queueing.py", line 501, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "C:\Users\w1xmo\miniconda3\envs\mrp\lib\site-packages\gradio\queueing.py", line 465, in call_prediction
    raise Exception(str(error) if show_error else None) from error
Exception: None
```

**Comment by Kevin-thu** [comment]
Sorry again for the inconvience! These errors result from different diffusers versions. Now hopefully we have fixed all the bugs, please try again.

**Comment by w1xmovies** [comment]
yep, it works
thanks!
